services:
  db:
    image: postgres:15
    restart: always
    container_name: shopping-list-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: shopping-list-redis
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    container_name: shopping-list-api
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  bot:
    build: .
    command: python -m app.bot.bot
    restart: always
    container_name: shopping-list-bot
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data: